name: Java project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19             # Update the name to indicate JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'            # Update the Java version to 19
        distribution: 'temurin'       # Specify the 'temurin' distribution for JDK 19
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
